import { z } from 'zod';
import {
  EMPLOYMENT_TYPE_VALUES,
  EMPLOYMENT_STATUS_VALUES,
  HEALTH_STATUS_VALUES,
  PAY_SCHEDULE_VALUES,
  SALARY_BASIS_VALUES,
  SALARY_FREQUENCY_VALUES,
} from './hr/people';
import { DATA_CLASSIFICATION_LEVELS, DATA_RESIDENCY_ZONES } from './tenant';
import {
  addressSchema,
  bankDetailsSchema,
  contactSchema,
  dateInputSchema,
  employmentPeriodSchema,
  jsonValueSchema,
  phoneSchema,
  salaryDetailSchema,
  certificationSchema,
} from './hr-people-schemas.shared';

export const employeeProfileSchema = z.object({
  id: z.uuid(),
  orgId: z.uuid(),
  userId: z.uuid(),
  email: z.email().nullable().optional(),
  personalEmail: z.email().nullable().optional(),
  firstName: z.string().nullable().optional(),
  lastName: z.string().nullable().optional(),
  displayName: z.string().nullable().optional(),
  photoUrl: z.string().nullable().optional(),
  employeeNumber: z.string(),
  jobTitle: z.string().nullable().optional(),
  employmentType: z.enum(EMPLOYMENT_TYPE_VALUES),
  employmentStatus: z.enum(EMPLOYMENT_STATUS_VALUES),
  departmentId: z.uuid().nullable().optional(),
  startDate: dateInputSchema.nullable().optional(),
  endDate: dateInputSchema.nullable().optional(),
  managerOrgId: z.uuid().nullable().optional(),
  managerUserId: z.uuid().nullable().optional(),
  annualSalary: z.number().nullable().optional(),
  hourlyRate: z.number().nullable().optional(),
  salaryAmount: z.number().nullable().optional(),
  salaryCurrency: z.string().nullable().optional(),
  salaryFrequency: z.enum(SALARY_FREQUENCY_VALUES).nullable().optional(),
  salaryBasis: z.enum(SALARY_BASIS_VALUES).nullable().optional(),
  paySchedule: z.enum(PAY_SCHEDULE_VALUES).nullable().optional(),
  costCenter: z.string().nullable().optional(),
  location: jsonValueSchema.optional(),
  niNumber: z.string().nullable().optional(),
  emergencyContact: contactSchema.nullable().optional(),
  nextOfKin: contactSchema.nullable().optional(),
  healthStatus: z.enum(HEALTH_STATUS_VALUES),
  workPermit: jsonValueSchema.optional(),
  bankDetails: bankDetailsSchema.nullable().optional(),
  metadata: jsonValueSchema.optional(),
  phone: phoneSchema.nullable().optional(),
  address: addressSchema.nullable().optional(),
  roles: z.array(z.string()).optional(),
  eligibleLeaveTypes: z.array(z.string()).optional(),
  employmentPeriods: z.array(employmentPeriodSchema).nullable().optional(),
  salaryDetails: salaryDetailSchema.nullable().optional(),
  skills: z.array(z.string()).nullable().optional(),
  certifications: z.array(certificationSchema).nullable().optional(),
  dataResidency: z.enum(DATA_RESIDENCY_ZONES).optional(),
  dataClassification: z.enum(DATA_CLASSIFICATION_LEVELS).optional(),
  auditSource: z.string().nullable().optional(),
  correlationId: z.string().nullable().optional(),
  schemaVersion: z.number().optional(),
  createdBy: z.uuid().nullable().optional(),
  updatedBy: z.uuid().nullable().optional(),
  retentionPolicy: z.string().nullable().optional(),
  retentionExpiresAt: dateInputSchema.nullable().optional(),
  erasureRequestedAt: dateInputSchema.nullable().optional(),
  erasureCompletedAt: dateInputSchema.nullable().optional(),
  erasureReason: z.string().nullable().optional(),
  erasureActorOrgId: z.uuid().nullable().optional(),
  erasureActorUserId: z.uuid().nullable().optional(),
  archivedAt: dateInputSchema.nullable().optional(),
  deletedAt: dateInputSchema.nullable().optional(),
  createdAt: dateInputSchema,
  updatedAt: dateInputSchema,
});
