import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { DevelopmentSecurityWidget } from "@/components/dev/DevelopmentSecurityWidget";
import { TenantThemeRegistry } from "@/components/theme/tenant-theme-registry";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ThemeProvider>
            {process.env.NODE_ENV === "development" ? <DevelopmentSecurityWidget /> : null}
            <TenantThemeRegistry orgId={null}>{children}</TenantThemeRegistry>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
