const CACHE_SCOPE_REGISTRY = {
    ABAC_POLICIES: 'abac-policies',
    ABSENCES: 'hr-absences',
    AUTH_LOGIN_PAGE: 'auth:login-page',
    AUTH_NOT_INVITED: 'auth:not-invited',
    BILLING_INVOICES: 'billing-invoices',
    BILLING_PAYMENT_METHODS: 'billing-payment-methods',
    BILLING_SUBSCRIPTION: 'billing-subscription',
    BILLING_UPCOMING: 'billing-upcoming',
    BRANDING: 'branding',
    CHECKLIST_INSTANCES: 'checklist-instances',
    CHECKLIST_TEMPLATES: 'checklist-templates',
    COMPLIANCE_CATEGORIES: 'compliance-categories',
    COMPLIANCE_ITEMS: 'compliance-items',
    COMPLIANCE_STATUS: 'compliance-status',
    COMPLIANCE_TEMPLATES: 'compliance-templates',
    DEPARTMENTS: 'departments',
    DLP_POLICIES: 'dlp-policies',
    DOCUMENT_VAULT: 'document-vault',
    ENTERPRISE_MANAGED_ORGS: 'enterprise-managed-orgs',
    HR_ABSENCE_AI_VALIDATION: 'hr:absences:ai-validation',
    HR_WORKER_ABSENCES: 'hr:absences',
    HR_WORKER_COMPLIANCE: 'hr:compliance',
    HR_WORKER_INTEGRATIONS: 'hr:integrations',
    HR_WORKER_LEAVE: 'hr:leave',
    HR_WORKER_ONBOARDING: 'hr:onboarding',
    HR_WORKER_PEOPLE_RETENTION: 'hr:people:retention',
    HR_WORKER_TRAINING: 'hr:training',
    HR_NOTIFICATIONS: 'hr-notifications',
    HR_POLICIES: 'hr-policies',
    HR_POLICY_ACKNOWLEDGMENTS: 'hr-policy-acknowledgments',
    HR_SETTINGS: 'hr-settings',
    LEAVE_BALANCES: 'leave-balances',
    LEAVE_POLICIES: 'leave-policies',
    LEAVE_REQUESTS: 'leave-requests',
    MEMBERS: 'members',
    NOTIFICATIONS: 'notifications',
    NOTIFICATION_PREFERENCES: 'notification-preferences',
    ONBOARDING_DOCUMENT_TEMPLATES: 'hr-onboarding-document-templates',
    ONBOARDING_EMAIL_SEQUENCES: 'hr-onboarding-email-sequences',
    ONBOARDING_FEEDBACK: 'hr-onboarding-feedback',
    ONBOARDING_INVITATIONS: 'hr-onboarding-invitations',
    ONBOARDING_MENTOR_ASSIGNMENTS: 'hr-onboarding-mentor-assignments',
    ONBOARDING_METRICS: 'hr-onboarding-metrics',
    ONBOARDING_PROVISIONING_TASKS: 'hr-onboarding-provisioning-tasks',
    ONBOARDING_WORKFLOW_TEMPLATES: 'hr-onboarding-workflow-templates',
    ORG_INVITATIONS: 'org-invitations',
    ORG_MEMBERSHIPS: 'org-memberships',
    ORG_PROFILE: 'org:profile',
    ORG_SETTINGS: 'org:settings',
    ORG_USERS: 'org-users',
    PEOPLE_CONTRACTS: 'hr-people-contracts',
    PEOPLE_PROFILES: 'hr-people-profiles',
    PERFORMANCE_GOALS: 'hr-performance-goals',
    PERFORMANCE_REVIEWS: 'hr-performance-reviews',
    PERMISSIONS: 'permissions',
    PLATFORM_BILLING_ASSIGNMENTS: 'platform:billing-assignments',
    PLATFORM_BILLING_PLANS: 'platform:billing-plans',
    PLATFORM_BREAK_GLASS: 'platform:break-glass',
    PLATFORM_IMPERSONATION: 'platform:impersonation',
    PLATFORM_SUPPORT: 'platform:support',
    PLATFORM_TENANTS: 'platform:tenants',
    PLATFORM_TOOLS: 'platform:tools',
    ROLES: 'roles',
    SECURITY_EVENTS: 'security-events',
    SECURITY_METRICS: 'security-metrics',
    TENANT_THEME: 'tenant-theme',
    TIME_ENTRIES: 'hr-time-entries',
    TRAINING_RECORDS: 'hr-training-records',
} as const;

export const CACHE_SCOPES = CACHE_SCOPE_REGISTRY;
export const CACHE_SCOPE_PLATFORM_TENANT_PREFIX = 'platform:tenant:' as const;

export type StaticCacheScope = (typeof CACHE_SCOPE_REGISTRY)[keyof typeof CACHE_SCOPE_REGISTRY];
export type DynamicCacheScope = `${typeof CACHE_SCOPE_PLATFORM_TENANT_PREFIX}${string}`;
export type CacheScope = StaticCacheScope | DynamicCacheScope;

const staticScopeSet: ReadonlySet<StaticCacheScope> = new Set(
    Object.values(CACHE_SCOPE_REGISTRY),
);

export function buildPlatformTenantCacheScope(tenantId: string): DynamicCacheScope {
    const normalized = tenantId.trim();
    if (normalized.length === 0) {
        throw new Error('Tenant ID is required to build platform tenant cache scope.');
    }
    return `${CACHE_SCOPE_PLATFORM_TENANT_PREFIX}${normalized}`;
}

export function isCacheScope(value: string): value is CacheScope {
    return (
        staticScopeSet.has(value as StaticCacheScope) ||
        value.startsWith(CACHE_SCOPE_PLATFORM_TENANT_PREFIX)
    );
}

export const CACHE_SCOPE_CHECKLIST_TEMPLATES = CACHE_SCOPE_REGISTRY.CHECKLIST_TEMPLATES;
export const CACHE_SCOPE_CHECKLIST_INSTANCES = CACHE_SCOPE_REGISTRY.CHECKLIST_INSTANCES;
export const CACHE_SCOPE_COMPLIANCE_TEMPLATES = CACHE_SCOPE_REGISTRY.COMPLIANCE_TEMPLATES;
export const CACHE_SCOPE_COMPLIANCE_CATEGORIES = CACHE_SCOPE_REGISTRY.COMPLIANCE_CATEGORIES;
export const CACHE_SCOPE_COMPLIANCE_ITEMS = CACHE_SCOPE_REGISTRY.COMPLIANCE_ITEMS;
export const CACHE_SCOPE_BRANDING = CACHE_SCOPE_REGISTRY.BRANDING;
export const CACHE_SCOPE_ROLES = CACHE_SCOPE_REGISTRY.ROLES;
export const CACHE_SCOPE_PERMISSIONS = CACHE_SCOPE_REGISTRY.PERMISSIONS;
export const CACHE_SCOPE_ABAC_POLICIES = CACHE_SCOPE_REGISTRY.ABAC_POLICIES;
export const CACHE_SCOPE_TENANT_THEME = CACHE_SCOPE_REGISTRY.TENANT_THEME;
export const CACHE_SCOPE_ENTERPRISE_MANAGED_ORGS = CACHE_SCOPE_REGISTRY.ENTERPRISE_MANAGED_ORGS;
export const CACHE_SCOPE_DEPARTMENTS = CACHE_SCOPE_REGISTRY.DEPARTMENTS;
export const CACHE_SCOPE_LEAVE_BALANCES = CACHE_SCOPE_REGISTRY.LEAVE_BALANCES;
export const CACHE_SCOPE_LEAVE_POLICIES = CACHE_SCOPE_REGISTRY.LEAVE_POLICIES;
export const CACHE_SCOPE_LEAVE_REQUESTS = CACHE_SCOPE_REGISTRY.LEAVE_REQUESTS;
export const CACHE_SCOPE_ABSENCES = CACHE_SCOPE_REGISTRY.ABSENCES;
export const CACHE_SCOPE_SECURITY_EVENTS = CACHE_SCOPE_REGISTRY.SECURITY_EVENTS;
export const CACHE_SCOPE_SECURITY_METRICS = CACHE_SCOPE_REGISTRY.SECURITY_METRICS;
export const CACHE_SCOPE_DLP_POLICIES = CACHE_SCOPE_REGISTRY.DLP_POLICIES;
export const CACHE_SCOPE_PEOPLE_PROFILES = CACHE_SCOPE_REGISTRY.PEOPLE_PROFILES;
export const CACHE_SCOPE_PEOPLE_CONTRACTS = CACHE_SCOPE_REGISTRY.PEOPLE_CONTRACTS;
export const CACHE_SCOPE_PERFORMANCE_REVIEWS = CACHE_SCOPE_REGISTRY.PERFORMANCE_REVIEWS;
export const CACHE_SCOPE_PERFORMANCE_GOALS = CACHE_SCOPE_REGISTRY.PERFORMANCE_GOALS;
export const CACHE_SCOPE_TIME_ENTRIES = CACHE_SCOPE_REGISTRY.TIME_ENTRIES;
export const CACHE_SCOPE_TRAINING_RECORDS = CACHE_SCOPE_REGISTRY.TRAINING_RECORDS;
export const CACHE_SCOPE_HR_POLICIES = CACHE_SCOPE_REGISTRY.HR_POLICIES;
export const CACHE_SCOPE_HR_POLICY_ACKNOWLEDGMENTS = CACHE_SCOPE_REGISTRY.HR_POLICY_ACKNOWLEDGMENTS;
export const CACHE_SCOPE_HR_NOTIFICATIONS = CACHE_SCOPE_REGISTRY.HR_NOTIFICATIONS;
export const CACHE_SCOPE_HR_SETTINGS = CACHE_SCOPE_REGISTRY.HR_SETTINGS;
export const CACHE_SCOPE_HR_WORKER_ABSENCES = CACHE_SCOPE_REGISTRY.HR_WORKER_ABSENCES;
export const CACHE_SCOPE_HR_WORKER_COMPLIANCE = CACHE_SCOPE_REGISTRY.HR_WORKER_COMPLIANCE;
export const CACHE_SCOPE_HR_WORKER_INTEGRATIONS = CACHE_SCOPE_REGISTRY.HR_WORKER_INTEGRATIONS;
export const CACHE_SCOPE_HR_WORKER_LEAVE = CACHE_SCOPE_REGISTRY.HR_WORKER_LEAVE;
export const CACHE_SCOPE_HR_WORKER_ONBOARDING = CACHE_SCOPE_REGISTRY.HR_WORKER_ONBOARDING;
export const CACHE_SCOPE_HR_WORKER_PEOPLE_RETENTION = CACHE_SCOPE_REGISTRY.HR_WORKER_PEOPLE_RETENTION;
export const CACHE_SCOPE_HR_WORKER_TRAINING = CACHE_SCOPE_REGISTRY.HR_WORKER_TRAINING;
export const CACHE_SCOPE_NOTIFICATION_PREFERENCES = CACHE_SCOPE_REGISTRY.NOTIFICATION_PREFERENCES;
export const CACHE_SCOPE_ONBOARDING_INVITATIONS = CACHE_SCOPE_REGISTRY.ONBOARDING_INVITATIONS;
export const CACHE_SCOPE_ONBOARDING_WORKFLOW_TEMPLATES = CACHE_SCOPE_REGISTRY.ONBOARDING_WORKFLOW_TEMPLATES;
export const CACHE_SCOPE_ONBOARDING_EMAIL_SEQUENCES = CACHE_SCOPE_REGISTRY.ONBOARDING_EMAIL_SEQUENCES;
export const CACHE_SCOPE_ONBOARDING_DOCUMENT_TEMPLATES = CACHE_SCOPE_REGISTRY.ONBOARDING_DOCUMENT_TEMPLATES;
export const CACHE_SCOPE_ONBOARDING_PROVISIONING_TASKS = CACHE_SCOPE_REGISTRY.ONBOARDING_PROVISIONING_TASKS;
export const CACHE_SCOPE_ONBOARDING_MENTOR_ASSIGNMENTS = CACHE_SCOPE_REGISTRY.ONBOARDING_MENTOR_ASSIGNMENTS;
export const CACHE_SCOPE_ONBOARDING_METRICS = CACHE_SCOPE_REGISTRY.ONBOARDING_METRICS;
export const CACHE_SCOPE_ONBOARDING_FEEDBACK = CACHE_SCOPE_REGISTRY.ONBOARDING_FEEDBACK;
export const CACHE_SCOPE_COMPLIANCE_STATUS = CACHE_SCOPE_REGISTRY.COMPLIANCE_STATUS;
export const CACHE_SCOPE_DOCUMENT_VAULT = CACHE_SCOPE_REGISTRY.DOCUMENT_VAULT;
export const CACHE_SCOPE_BILLING_SUBSCRIPTION = CACHE_SCOPE_REGISTRY.BILLING_SUBSCRIPTION;
export const CACHE_SCOPE_BILLING_PAYMENT_METHODS = CACHE_SCOPE_REGISTRY.BILLING_PAYMENT_METHODS;
export const CACHE_SCOPE_BILLING_INVOICES = CACHE_SCOPE_REGISTRY.BILLING_INVOICES;
export const CACHE_SCOPE_BILLING_UPCOMING = CACHE_SCOPE_REGISTRY.BILLING_UPCOMING;
export const CACHE_SCOPE_MEMBERS = CACHE_SCOPE_REGISTRY.MEMBERS;
export const CACHE_SCOPE_NOTIFICATIONS = CACHE_SCOPE_REGISTRY.NOTIFICATIONS;
export const CACHE_SCOPE_ORG_INVITATIONS = CACHE_SCOPE_REGISTRY.ORG_INVITATIONS;
export const CACHE_SCOPE_ORG_MEMBERSHIPS = CACHE_SCOPE_REGISTRY.ORG_MEMBERSHIPS;
export const CACHE_SCOPE_ORG_PROFILE = CACHE_SCOPE_REGISTRY.ORG_PROFILE;
export const CACHE_SCOPE_ORG_SETTINGS = CACHE_SCOPE_REGISTRY.ORG_SETTINGS;
export const CACHE_SCOPE_ORG_USERS = CACHE_SCOPE_REGISTRY.ORG_USERS;
export const CACHE_SCOPE_PLATFORM_BILLING_ASSIGNMENTS = CACHE_SCOPE_REGISTRY.PLATFORM_BILLING_ASSIGNMENTS;
export const CACHE_SCOPE_PLATFORM_BILLING_PLANS = CACHE_SCOPE_REGISTRY.PLATFORM_BILLING_PLANS;
export const CACHE_SCOPE_PLATFORM_BREAK_GLASS = CACHE_SCOPE_REGISTRY.PLATFORM_BREAK_GLASS;
export const CACHE_SCOPE_PLATFORM_IMPERSONATION = CACHE_SCOPE_REGISTRY.PLATFORM_IMPERSONATION;
export const CACHE_SCOPE_PLATFORM_SUPPORT = CACHE_SCOPE_REGISTRY.PLATFORM_SUPPORT;
export const CACHE_SCOPE_PLATFORM_TENANTS = CACHE_SCOPE_REGISTRY.PLATFORM_TENANTS;
export const CACHE_SCOPE_PLATFORM_TOOLS = CACHE_SCOPE_REGISTRY.PLATFORM_TOOLS;
export const CACHE_SCOPE_AUTH_LOGIN_PAGE = CACHE_SCOPE_REGISTRY.AUTH_LOGIN_PAGE;
export const CACHE_SCOPE_AUTH_NOT_INVITED = CACHE_SCOPE_REGISTRY.AUTH_NOT_INVITED;
export const CACHE_SCOPE_HR_ABSENCE_AI_VALIDATION = CACHE_SCOPE_REGISTRY.HR_ABSENCE_AI_VALIDATION;
