import { RoleScope } from '@/server/types/prisma';
import type { OrgPermissionMap } from './access-control';
import type { OrgRoleKey } from './role-constants';
import { ROLE_PERMISSION_STATEMENTS } from './role-permission-statements';

export const globalAdminTemplate = {
  name: 'globalAdmin' as const satisfies OrgRoleKey,
  description: 'Global administrator with full platform access.',
  scope: RoleScope.GLOBAL,
  permissions: {
    platformTenants: ROLE_PERMISSION_STATEMENTS.platformTenants,
    platformBillingPlans: ROLE_PERMISSION_STATEMENTS.platformBillingPlans,
    platformTools: ROLE_PERMISSION_STATEMENTS.platformTools,
    platformDocuments: ROLE_PERMISSION_STATEMENTS.platformDocuments,
    platformSupport: ROLE_PERMISSION_STATEMENTS.platformSupport,
    platformImpersonation: ROLE_PERMISSION_STATEMENTS.platformImpersonation,
    platformBreakGlass: ROLE_PERMISSION_STATEMENTS.platformBreakGlass,
    platformSettings: ROLE_PERMISSION_STATEMENTS.platformSettings,
    'org.settings': ROLE_PERMISSION_STATEMENTS['org.settings'],
    member: ROLE_PERMISSION_STATEMENTS.member,
    invitation: ROLE_PERMISSION_STATEMENTS.invitation,
    audit: ROLE_PERMISSION_STATEMENTS.audit,
    cache: ROLE_PERMISSION_STATEMENTS.cache,
    residency: ROLE_PERMISSION_STATEMENTS.residency,
    'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
    'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
    'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
    'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
    'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
    'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
    'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
    'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
    'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
    'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
    'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
    'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
    'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
    'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
    'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
    'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
    'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
    'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
    'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
    'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
    'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
    'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
    'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
    'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
    'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
    'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
    'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
    'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
  } satisfies OrgPermissionMap,
  inherits: [],
  isSystem: true,
  isDefault: true,
};

export const ownerTemplate = {
  name: 'owner' as const satisfies OrgRoleKey,
  description: 'Organization owner with full org access.',
  scope: RoleScope.ORG,
  permissions: {
    'org.settings': ROLE_PERMISSION_STATEMENTS['org.settings'],
    member: ROLE_PERMISSION_STATEMENTS.member,
    invitation: ROLE_PERMISSION_STATEMENTS.invitation,
    audit: ROLE_PERMISSION_STATEMENTS.audit,
    cache: ROLE_PERMISSION_STATEMENTS.cache,
    residency: ROLE_PERMISSION_STATEMENTS.residency,
    'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
    'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
    'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
    'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
    'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
    'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
    'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
    'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
    'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
    'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
    'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
    'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
    'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
    'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
    'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
    'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
    'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
    'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
    'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
    'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
    'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
    'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
    'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
    'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
    'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
    'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
    'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
    'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
  } satisfies OrgPermissionMap,
  inherits: [],
  isSystem: true,
  isDefault: true,
};
