import { RoleScope } from '@prisma/client';
import type { OrgPermissionMap } from './access-control';
import type { OrgRoleKey } from './role-constants';
export interface RoleTemplate {
    name: OrgRoleKey;
    description: string;
    scope: RoleScope;
    permissions: OrgPermissionMap;
    inherits?: OrgRoleKey[];
    isSystem?: boolean;
    isDefault?: boolean;
}
export const ROLE_PERMISSION_STATEMENTS: Record<string, readonly string[]> = {
    audit: ['read', 'write'],
    cache: ['tag', 'invalidate'],
    invitation: ['create', 'cancel'],
    member: ['read', 'invite', 'update', 'remove'],
    'org.settings': ['create', 'read', 'update', 'delete', 'governance'],
    residency: ['enforce'],
    'hr.absence': ['read', 'list', 'create', 'update', 'delete', 'acknowledge', 'cancel'],
    'hr.absence.settings': ['read', 'update'],
    'hr.absence.attachment': ['create', 'delete'],
    'hr.compliance.item': ['read', 'list', 'create', 'update', 'delete', 'review', 'assign'],
    'hr.compliance.template': ['read', 'list', 'create', 'update', 'delete'],
    'hr.compliance.review': ['review'],
    'hr.leave.request': ['read', 'list', 'create', 'update', 'delete', 'approve', 'reject', 'cancel'],
    'hr.leave.balance': ['read', 'adjust'],
    'hr.leave.policy': ['read', 'list', 'create', 'update', 'delete'],
    'hr.leave.type': ['read', 'list', 'create', 'update', 'delete'],
    'hr.notification': ['read', 'list', 'create', 'update', 'delete'],
    'hr.reminder': ['read', 'list', 'create', 'update'],
    'hr.onboarding.invite': ['read', 'send'],
    'hr.onboarding.task': ['read', 'list', 'create', 'update', 'delete', 'complete'],
    'hr.onboarding.checklist': ['read', 'update', 'complete'],
    'hr.checklist.template': ['read', 'list', 'create', 'update', 'delete'],
    'hr.people.profile': ['read', 'list', 'create', 'update', 'delete'],
    'hr.people.contract': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.review': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.goal': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.feedback': ['create', 'update'],
    'hr.policy': ['read', 'list', 'create', 'update', 'delete', 'publish', 'unpublish'],
    'hr.policy.acknowledgment': ['acknowledge'],
    'hr.settings': ['read', 'update'],
    'hr.time.entry': ['read', 'list', 'create', 'update', 'delete', 'approve'],
    'hr.time.sheet': ['read', 'list', 'approve'],
    'hr.training.record': ['read', 'list', 'create', 'update', 'delete'],
    'hr.training.enrollment': ['enroll', 'complete'],
};

export const ROLE_TEMPLATES: Record<OrgRoleKey, RoleTemplate> = {
    globalAdmin: {
        name: 'globalAdmin',
        description: 'Global administrator with full platform access.',
        scope: RoleScope.GLOBAL,
        permissions: {
            'org.settings': ROLE_PERMISSION_STATEMENTS['org.settings'],
            member: ROLE_PERMISSION_STATEMENTS.member,
            invitation: ROLE_PERMISSION_STATEMENTS.invitation,
            audit: ROLE_PERMISSION_STATEMENTS.audit,
            cache: ROLE_PERMISSION_STATEMENTS.cache,
            residency: ROLE_PERMISSION_STATEMENTS.residency,
            'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
            'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
            'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
            'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
            'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
            'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
            'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
            'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
            'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
            'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
            'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
            'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
            'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
            'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
            'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
            'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
            'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
            'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
            'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
            'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
            'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
            'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
            'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
            'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
            'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
            'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
            'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
            'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
        },
        inherits: [],
        isSystem: true,
        isDefault: true,
    },
    owner: {
        name: 'owner',
        description: 'Organization owner with full org access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ROLE_PERMISSION_STATEMENTS['org.settings'],
            member: ROLE_PERMISSION_STATEMENTS.member,
            invitation: ROLE_PERMISSION_STATEMENTS.invitation,
            audit: ROLE_PERMISSION_STATEMENTS.audit,
            cache: ROLE_PERMISSION_STATEMENTS.cache,
            residency: ROLE_PERMISSION_STATEMENTS.residency,
            'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
            'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
            'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
            'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
            'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
            'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
            'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
            'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
            'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
            'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
            'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
            'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
            'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
            'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
            'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
            'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
            'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
            'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
            'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
            'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
            'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
            'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
            'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
            'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
            'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
            'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
            'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
            'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
        },
        inherits: [],
        isSystem: true,
        isDefault: true,
    },
    orgAdmin: {
        name: 'orgAdmin',
        description: 'Organization administrator with HR admin access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ['read', 'update'],
            member: ['read', 'invite', 'update'],
            invitation: ROLE_PERMISSION_STATEMENTS.invitation,
            cache: ROLE_PERMISSION_STATEMENTS.cache,
            'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
            'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
            'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
            'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
            'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
            'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
            'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
            'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
            'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
            'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
            'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
            'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
            'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
            'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
            'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
            'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
            'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
            'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
            'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
            'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
            'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
            'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
            'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
            'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
            'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
            'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
            'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
            'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
        },
        inherits: ['member'],
        isSystem: true,
        isDefault: true,
    },
    hrAdmin: {
        name: 'hrAdmin',
        description: 'HR administrator with full HR module access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ['read'],
            member: ['read', 'invite'],
            invitation: ROLE_PERMISSION_STATEMENTS.invitation,
            'hr.absence': ROLE_PERMISSION_STATEMENTS['hr.absence'],
            'hr.absence.settings': ROLE_PERMISSION_STATEMENTS['hr.absence.settings'],
            'hr.absence.attachment': ROLE_PERMISSION_STATEMENTS['hr.absence.attachment'],
            'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
            'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
            'hr.compliance.review': ROLE_PERMISSION_STATEMENTS['hr.compliance.review'],
            'hr.leave.request': ROLE_PERMISSION_STATEMENTS['hr.leave.request'],
            'hr.leave.balance': ROLE_PERMISSION_STATEMENTS['hr.leave.balance'],
            'hr.leave.policy': ROLE_PERMISSION_STATEMENTS['hr.leave.policy'],
            'hr.leave.type': ROLE_PERMISSION_STATEMENTS['hr.leave.type'],
            'hr.notification': ROLE_PERMISSION_STATEMENTS['hr.notification'],
            'hr.reminder': ROLE_PERMISSION_STATEMENTS['hr.reminder'],
            'hr.onboarding.invite': ROLE_PERMISSION_STATEMENTS['hr.onboarding.invite'],
            'hr.onboarding.task': ROLE_PERMISSION_STATEMENTS['hr.onboarding.task'],
            'hr.onboarding.checklist': ROLE_PERMISSION_STATEMENTS['hr.onboarding.checklist'],
            'hr.checklist.template': ROLE_PERMISSION_STATEMENTS['hr.checklist.template'],
            'hr.people.profile': ROLE_PERMISSION_STATEMENTS['hr.people.profile'],
            'hr.people.contract': ROLE_PERMISSION_STATEMENTS['hr.people.contract'],
            'hr.performance.review': ROLE_PERMISSION_STATEMENTS['hr.performance.review'],
            'hr.performance.goal': ROLE_PERMISSION_STATEMENTS['hr.performance.goal'],
            'hr.performance.feedback': ROLE_PERMISSION_STATEMENTS['hr.performance.feedback'],
            'hr.policy': ROLE_PERMISSION_STATEMENTS['hr.policy'],
            'hr.policy.acknowledgment': ROLE_PERMISSION_STATEMENTS['hr.policy.acknowledgment'],
            'hr.settings': ROLE_PERMISSION_STATEMENTS['hr.settings'],
            'hr.time.entry': ROLE_PERMISSION_STATEMENTS['hr.time.entry'],
            'hr.time.sheet': ROLE_PERMISSION_STATEMENTS['hr.time.sheet'],
            'hr.training.record': ROLE_PERMISSION_STATEMENTS['hr.training.record'],
            'hr.training.enrollment': ROLE_PERMISSION_STATEMENTS['hr.training.enrollment'],
        },
        inherits: ['member'],
        isSystem: true,
        isDefault: true,
    },
    manager: {
        name: 'manager',
        description: 'Manager with team-level HR access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ['read'],
            member: ['read'],
            'hr.people.profile': ['read', 'list'],
            'hr.people.contract': ['read', 'list'],
            'hr.absence': ['read', 'list', 'acknowledge'],
            'hr.absence.attachment': ['create', 'delete'],
            'hr.compliance.item': ['read', 'list'],
            'hr.leave.request': ['read', 'list', 'approve'],
            'hr.leave.balance': ['read'],
            'hr.notification': ['read', 'list'],
            'hr.performance.review': ['read', 'list', 'create', 'update'],
            'hr.performance.goal': ['read', 'list', 'create', 'update'],
            'hr.time.entry': ['read', 'list', 'approve'],
            'hr.time.sheet': ['read', 'list', 'approve'],
            'hr.training.record': ['read', 'list'],
        },
        inherits: ['member'],
        isSystem: true,
        isDefault: true,
    },
    compliance: {
        name: 'compliance',
        description: 'Compliance officer with audit access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ['read'],
            audit: ROLE_PERMISSION_STATEMENTS.audit,
            residency: ROLE_PERMISSION_STATEMENTS.residency,
            'hr.people.profile': ['read', 'list'],
            'hr.compliance.item': ROLE_PERMISSION_STATEMENTS['hr.compliance.item'],
            'hr.compliance.template': ROLE_PERMISSION_STATEMENTS['hr.compliance.template'],
            'hr.policy': ['read', 'list'],
        },
        inherits: ['member'],
        isSystem: true,
        isDefault: true,
    },
    member: {
        name: 'member',
        description: 'Standard member with self-service HR access.',
        scope: RoleScope.ORG,
        permissions: {
            'org.settings': ['read'],
            'hr.people.profile': ['read', 'list', 'update'],
            'hr.people.contract': ['read', 'list'],
            'hr.absence': ['read', 'list', 'create'],
            'hr.absence.attachment': ['create', 'delete'],
            'hr.compliance.item': ['read', 'list', 'update'],
            'hr.leave.request': ['read', 'list', 'create', 'cancel'],
            'hr.leave.balance': ['read'],
            'hr.notification': ['read', 'list'],
            'hr.performance.review': ['read', 'list'],
            'hr.performance.goal': ['read', 'list'],
            'hr.policy': ['read', 'list'],
            'hr.policy.acknowledgment': ['acknowledge'],
            'hr.time.entry': ['read', 'list', 'create', 'update'],
            'hr.time.sheet': ['read', 'list'],
            'hr.training.record': ['read', 'list'],
            'hr.training.enrollment': ['enroll', 'complete'],
        },
        inherits: [],
        isSystem: true,
        isDefault: true,
    },
};

export function resolveRoleTemplate(roleKey: OrgRoleKey): RoleTemplate {
    return ROLE_TEMPLATES[roleKey];
}
export function combineRoleTemplates(roleKeys: OrgRoleKey[]): OrgPermissionMap {
    return roleKeys.reduce<OrgPermissionMap>((accumulator, key) => {
        const statements = ROLE_TEMPLATES[key].permissions as Record<string, string[]>;
        for (const [resource, actions] of Object.entries(statements)) {
            const existing = accumulator[resource] ?? [];
            const merged = new Set([...(existing), ...(Array.isArray(actions) ? actions : [])]);
            accumulator[resource] = Array.from(merged);
        }
        return accumulator;
    }, {});
}
