import type { OrgPermissionMap } from './access-control';

export const ROLE_PERMISSION_STATEMENTS: Record<string, readonly string[]> = {
    audit: ['read', 'write'],
    cache: ['tag', 'invalidate'],
    invitation: ['create', 'cancel'],
    member: ['read', 'invite', 'update', 'remove'],
    platformTenants: ['read', 'update'],
    platformBillingPlans: ['read', 'create', 'update', 'assign'],
    platformTools: ['read', 'execute'],
    platformDocuments: ['read', 'download'],
    platformSupport: ['read', 'create', 'update', 'assign'],
    platformImpersonation: ['read', 'request', 'approve', 'start', 'stop'],
    platformBreakGlass: ['request', 'approve', 'read'],
    platformSettings: ['read', 'update'],
    'org.settings': ['create', 'read', 'update', 'delete', 'governance'],
    residency: ['enforce'],
    'hr.absence': ['read', 'list', 'create', 'update', 'delete', 'acknowledge', 'cancel'],
    'hr.absence.settings': ['read', 'update'],
    'hr.absence.attachment': ['create', 'delete'],
    'hr.compliance.item': ['read', 'list', 'create', 'update', 'delete', 'review', 'assign'],
    'hr.compliance.template': ['read', 'list', 'create', 'update', 'delete'],
    'hr.compliance.review': ['review'],
    'hr.leave.request': ['read', 'list', 'create', 'update', 'delete', 'approve', 'reject', 'cancel'],
    'hr.leave.balance': ['read', 'adjust'],
    'hr.leave.policy': ['read', 'list', 'create', 'update', 'delete'],
    'hr.leave.type': ['read', 'list', 'create', 'update', 'delete'],
    'hr.notification': ['read', 'list', 'create', 'update', 'delete'],
    'hr.reminder': ['read', 'list', 'create', 'update'],
    'hr.onboarding.invite': ['read', 'send'],
    'hr.onboarding.task': ['read', 'list', 'create', 'update', 'delete', 'complete'],
    'hr.onboarding.checklist': ['read', 'update', 'complete'],
    'hr.checklist.template': ['read', 'list', 'create', 'update', 'delete'],
    'hr.people.profile': ['read', 'list', 'create', 'update', 'delete'],
    'hr.people.contract': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.review': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.goal': ['read', 'list', 'create', 'update', 'delete'],
    'hr.performance.feedback': ['create', 'update'],
    'hr.policy': ['read', 'list', 'create', 'update', 'delete', 'publish', 'unpublish'],
    'hr.policy.acknowledgment': ['acknowledge'],
    'hr.settings': ['read', 'update'],
    'hr.time.entry': ['read', 'list', 'create', 'update', 'delete', 'approve'],
    'hr.time.sheet': ['read', 'list', 'approve'],
    'hr.training.record': ['read', 'list', 'create', 'update', 'delete'],
    'hr.training.enrollment': ['enroll', 'complete'],
} satisfies OrgPermissionMap;
